POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "This is a test message",
  "user_id": "${userID1}"
}

###
POST http://localhost:8080/api/chirps
Content-Type: application/json

{
  "body": "If you're committed enough, you can make any story work.",
  "user_id": "${userID1}"
}

### Test GetChirps
GET http://localhost:8080/api/chirps

### Test GetChirp with ID
GET http://localhost:8080/api/chirps/5493fbe5-9a18-4f66-b188-fa9f77fd6a23

### Test GetChirps with Authorization
GET http://localhost:8080/api/chirps
Authorization: Test