### Reset server / database
POST http://localhost:8080/admin/reset

### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "1234567890"
}

### Login user
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "1234567890"
}

###
POST http://localhost:8080/api/refresh
Content-Type: application/json
Authorization: Bearer e6ce5f7e692c963351486c326a68b0f07db798d2d2fe1b9833e7698e711767ee

### Test metrics
GET http://localhost:8080/admin/metrics