### Reset server / database
POST http://localhost:8080/admin/reset

### Create user
POST http://localhost:8080/api/users
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "1234567890"
}

### Login user
POST http://localhost:8080/api/login
Content-Type: application/json

{
    "email": "user@example.com",
    "password": "1234567890"
}